Work in Google Colab. Calculation of the forecasted happiness indicator.

1. Input the vector (matrix of size 8) A. Vector A represents your life balance wheel metrics.

In [1]:
import numpy as np

a = np.array([4,3,2,5,7,4,3,7])
print(a)

[4 3 2 5 7 4 3 7]


2. Calculate the sum of the elements of vector A. This is your current “happiness indicator.”

In [2]:
import numpy as np

sum_a = np.sum(a)
print(a)

35


3. Input vector B. These are the metrics of your life distribution across different spheres.

In [3]:
import numpy as np

b = np.array([4,7,56,2,20,12,1,4])
print(b)

[ 4  7 56  2 20 12  1  4]


4. Calculate vector C, which equals C = A / B. This is your life efficiency showing how many "happiness points" you get for 1 hour per week that you dedicate to a particular sphere.

In [4]:
import numpy as np

c = a/b
print(c)

[1.         0.42857143 0.03571429 2.5        0.35       0.33333333
 3.         1.75      ]


5. Make up your mind to do rapid changes in your life. Think how you would like to redistribute your time. Record the result of the new time distribution in the Google Sheets in the column "Redistributed Number of Hours" on the sheet "Mathematical Apparatus" and in Colab input it as vector D.

In [5]:
import numpy as np

d = np.array([12,14,30,8,10,18,6,8])
print(d)

[12 14 30  8 10 18  6  8]


6. Calculate vector E as E = D * C. This is your forecasted satisfaction with the respective life spheres.

In [6]:
import numpy as np

e = d*c
print(e)

[12.          6.          1.07142857 20.          3.5         6.
 18.         14.        ]


7. Calculate the sum of the vector E elements, which will show you the forecasted happiness indicator if you make rapid changes in your life by redistributing your time.

In [13]:
import numpy as np

sum_e = np.sum(e)
print(int(sum_e))

80
